### ISSUE TITLE
дублювання блоків коду

### ISSUE THREAD

**Issue by pecourses** [OleksandraShkutova/css-intro#2]
https://github.com/OleksandraShkutova/css-intro/blob/45a6b39951cedac587cfee02e77910a68069373c/assets/css/style.css#L64-L85
- якщо кілька блоків практично одноипні та мають спільні набори правил, то було зручно винести їх в спільний опис:
```css
.box-a,
.box-b,
.box-c {
  display: inline-block;
  width: calc(100% / 3);
  padding: 20px;
  font-size: 17px;
}

.box-b {
  color: #926239;
  background-color: #f4f4f4;
}
``` 
Таким чином ми отримуємо єдине джерело істини. Це зручно тим, що якщо, наприклад, нам згодом при підтримці продукту знадобиться внести якісь зміни, наприклад, змінити padding для всіх цих блоків, то ми зможемо це зробити в одному рядку, а не шукати всі 3 рядки окремо.
